"""flatten sites into landmarks

Revision ID: 5bfdc4563451
Revises: 442ccac92fa7
Create Date: 2026-08-31 11:52:31.252745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bfdc4563451'
down_revision: Union[str, None] = '442ccac92fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: reordered by hand — landmarks.site_id (which FKs to sites) must be
    # dropped before the sites table itself, or Postgres refuses the DROP TABLE.
    op.add_column('itinerary_stops', sa.Column('landmark_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'itinerary_stops', 'landmarks', ['landmark_id'], ['id'])
    op.drop_column('itinerary_stops', 'site')
    op.add_column('landmarks', sa.Column('avg_visit_minutes', sa.Integer(), nullable=False))
    op.add_column('landmarks', sa.Column('accessibility_notes', sa.Text(), nullable=False))
    op.drop_constraint('landmarks_site_id_fkey', 'landmarks', type_='foreignkey')
    op.drop_column('landmarks', 'site_id')
    op.drop_table('sites')
    op.add_column('providers', sa.Column('landmark_ids', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('providers', 'sites')
    op.add_column('trip_requests', sa.Column('landmark_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'trip_requests', 'landmarks', ['landmark_id'], ['id'])
    op.drop_column('trip_requests', 'site')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: reordered by hand — sites must exist before landmarks.site_id's FK
    # can reference it.
    op.add_column('trip_requests', sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trip_requests', type_='foreignkey')
    op.drop_column('trip_requests', 'landmark_id')
    op.add_column('providers', sa.Column('sites', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('providers', 'landmark_ids')
    op.create_table('sites',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_ar', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description_ar', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('avg_visit_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accessibility_notes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sites_pkey')
    )
    op.add_column('landmarks', sa.Column('site_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('landmarks_site_id_fkey', 'landmarks', 'sites', ['site_id'], ['id'])
    op.drop_column('landmarks', 'accessibility_notes')
    op.drop_column('landmarks', 'avg_visit_minutes')
    op.add_column('itinerary_stops', sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'itinerary_stops', type_='foreignkey')
    op.drop_column('itinerary_stops', 'landmark_id')
    # ### end Alembic commands ###
