"""add landmark_images gallery table

Revision ID: 628887a654a2
Revises: a314e04c4806
Create Date: 2026-09-03 12:09:31.206236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628887a654a2'
down_revision: Union[str, None] = 'a314e04c4806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmark_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landmark_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('license', sa.String(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=False),
    sa.Column('caption_en', sa.Text(), nullable=True),
    sa.Column('caption_ar', sa.Text(), nullable=True),
    sa.Column('researcher', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_landmark_image_position'),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landmark_id', 'position', name='uq_landmark_image_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landmark_images')
    # ### end Alembic commands ###
