"""add lat lon source_url to landmarks

Revision ID: 8ec35c46a400
Revises: 5bfdc4563451
Create Date: 2026-08-31 13:47:59.173402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec35c46a400'
down_revision: Union[str, None] = '5bfdc4563451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landmarks', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('landmarks', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('landmarks', sa.Column('source_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landmarks', 'source_url')
    op.drop_column('landmarks', 'lon')
    op.drop_column('landmarks', 'lat')
    # ### end Alembic commands ###
