"""swipe deck, phase 2 depth, advisors and bookings; drop bidding

Revision ID: a314e04c4806
Revises: 8ec35c46a400
Create Date: 2026-09-03 11:07:04.943255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a314e04c4806'
down_revision: Union[str, None] = '8ec35c46a400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('itinerary_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('price_jod', sa.Float(), nullable=False),
    sa.Column('price_is_mock', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bids')
    op.drop_table('trip_requests')
    op.add_column('itineraries', sa.Column('trip_days', sa.Integer(), server_default='1', nullable=False))
    op.add_column('itinerary_stops', sa.Column('kind', sa.String(), server_default='landmark', nullable=False))
    op.add_column('itinerary_stops', sa.Column('day', sa.Integer(), server_default='1', nullable=False))
    op.add_column('itinerary_stops', sa.Column('travel_minutes', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('itinerary_stops', 'landmark_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('landmarks', sa.Column('parent_id', sa.String(), nullable=True))
    op.add_column('landmarks', sa.Column('category', sa.String(), nullable=True))
    op.add_column('landmarks', sa.Column('history_en', sa.Text(), nullable=True))
    op.add_column('landmarks', sa.Column('history_ar', sa.Text(), nullable=True))
    op.add_column('landmarks', sa.Column('significance_en', sa.Text(), nullable=True))
    op.add_column('landmarks', sa.Column('significance_ar', sa.Text(), nullable=True))
    op.add_column('landmarks', sa.Column('narration_en', sa.Text(), nullable=True))
    op.add_column('landmarks', sa.Column('narration_ar', sa.Text(), nullable=True))
    op.add_column('landmarks', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('landmarks', sa.Column('best_time_to_visit', sa.Text(), nullable=True))
    op.add_column('landmarks', sa.Column('requires_guide', sa.Boolean(), nullable=True))
    op.add_column('landmarks', sa.Column('entrance_fee_notes', sa.Text(), nullable=True))
    op.add_column('landmarks', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('providers', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('providers', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('providers', sa.Column('hourly_rate_jod', sa.Float(), nullable=True))
    op.add_column('providers', sa.Column('bio_en', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('bio_ar', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'photo_url')
    op.drop_column('providers', 'bio_ar')
    op.drop_column('providers', 'bio_en')
    op.drop_column('providers', 'hourly_rate_jod')
    op.drop_column('providers', 'lon')
    op.drop_column('providers', 'lat')
    op.drop_column('landmarks', 'active')
    op.drop_column('landmarks', 'entrance_fee_notes')
    op.drop_column('landmarks', 'requires_guide')
    op.drop_column('landmarks', 'best_time_to_visit')
    op.drop_column('landmarks', 'difficulty')
    op.drop_column('landmarks', 'narration_ar')
    op.drop_column('landmarks', 'narration_en')
    op.drop_column('landmarks', 'significance_ar')
    op.drop_column('landmarks', 'significance_en')
    op.drop_column('landmarks', 'history_ar')
    op.drop_column('landmarks', 'history_en')
    op.drop_column('landmarks', 'category')
    op.drop_column('landmarks', 'parent_id')
    op.alter_column('itinerary_stops', 'landmark_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('itinerary_stops', 'travel_minutes')
    op.drop_column('itinerary_stops', 'day')
    op.drop_column('itinerary_stops', 'kind')
    op.drop_column('itineraries', 'trip_days')
    op.create_table('trip_requests',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('itinerary_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('group_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('specialty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('accessibility_needs', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('landmark_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], name='trip_requests_itinerary_id_fkey'),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], name='trip_requests_landmark_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trip_requests_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('bids',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name='bids_provider_id_fkey'),
    sa.ForeignKeyConstraint(['request_id'], ['trip_requests.id'], name='bids_request_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bids_pkey')
    )
    op.drop_table('bookings')
    # ### end Alembic commands ###
