"""trip lifecycle: meeting-point PIN, start/end times, settled price

Revision ID: db3fbb9eada4
Revises: df2ecd700220
Create Date: 2026-09-07 10:56:54.405884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3fbb9eada4'
down_revision: Union[str, None] = 'df2ecd700220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pin', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('final_price_jod', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'final_price_jod')
    op.drop_column('bookings', 'ended_at')
    op.drop_column('bookings', 'started_at')
    op.drop_column('bookings', 'pin')
    # ### end Alembic commands ###
