"""guide app: offerings, availability blocks, booking lifecycle

Revision ID: df2ecd700220
Revises: e9b8ad5b16fc
Create Date: 2026-09-04 19:47:53.005272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2ecd700220'
down_revision: Union[str, None] = 'e9b8ad5b16fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'date', 'start_time', name='uq_availability_slot')
    )
    op.create_index(op.f('ix_availability_blocks_date'), 'availability_blocks', ['date'], unique=False)
    op.create_index(op.f('ix_availability_blocks_provider_id'), 'availability_blocks', ['provider_id'], unique=False)
    op.create_table('offerings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_ar', sa.String(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('max_group', sa.Integer(), nullable=False),
    sa.Column('price_jod', sa.Float(), nullable=False),
    sa.Column('landmark_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offerings_provider_id'), 'offerings', ['provider_id'], unique=False)
    op.add_column('bookings', sa.Column('offering_id', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('responds_by', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'bookings', 'offerings', ['offering_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'responds_by')
    op.drop_column('bookings', 'offering_id')
    op.drop_index(op.f('ix_offerings_provider_id'), table_name='offerings')
    op.drop_table('offerings')
    op.drop_index(op.f('ix_availability_blocks_provider_id'), table_name='availability_blocks')
    op.drop_index(op.f('ix_availability_blocks_date'), table_name='availability_blocks')
    op.drop_table('availability_blocks')
    # ### end Alembic commands ###
